deploy:
  stage: deploy
  only:
    - master

  image: klakegg/hugo:ext-debian-ci
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - mkdir ~/.ssh
    - ssh-keyscan 193.53.251.11 >> ~/.ssh/known_hosts
    - apt-get update && apt-get install git rsync
    - echo "-.-.-.-.-.-.-.-.-.-.-.-."
    - git submodule init
    - git submodule update --remote --merge
    - echo "-.-.-.-.-.-.-.-.-.-.-.-."
    - echo "$PWD"
    - hugo
    - rsync -avz -e "ssh -o StrictHostKeyChecking=no" --exclude-from=rsync-excl.txt /builds/buzigde/buzigde/public/ $SSH_USER@193.53.251.11:/home/www/p582623/html/buzigde/
